// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmd-4eos5ESnpgIXBbRkzkPZNH8bCVDhY',
    appId: '1:220649831521:web:ad06f4edd0ea9075c3fe20',
    messagingSenderId: '220649831521',
    projectId: 'flutter-create-mywallet',
    authDomain: 'flutter-create-mywallet.firebaseapp.com',
    storageBucket: 'flutter-create-mywallet.firebasestorage.app',
    measurementId: 'G-C5064YYSMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRtrxQqF7YFotLHwoXlE22mIkKOoyj82A',
    appId: '1:220649831521:android:69a0eed881d3a0f3c3fe20',
    messagingSenderId: '220649831521',
    projectId: 'flutter-create-mywallet',
    storageBucket: 'flutter-create-mywallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArz3njiWc4yvDzSy-0cC9hWG6sCDD8AXM',
    appId: '1:220649831521:ios:a6c1cde423d3fe95c3fe20',
    messagingSenderId: '220649831521',
    projectId: 'flutter-create-mywallet',
    storageBucket: 'flutter-create-mywallet.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArz3njiWc4yvDzSy-0cC9hWG6sCDD8AXM',
    appId: '1:220649831521:ios:a6c1cde423d3fe95c3fe20',
    messagingSenderId: '220649831521',
    projectId: 'flutter-create-mywallet',
    storageBucket: 'flutter-create-mywallet.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmd-4eos5ESnpgIXBbRkzkPZNH8bCVDhY',
    appId: '1:220649831521:web:c4037f859e7e8764c3fe20',
    messagingSenderId: '220649831521',
    projectId: 'flutter-create-mywallet',
    authDomain: 'flutter-create-mywallet.firebaseapp.com',
    storageBucket: 'flutter-create-mywallet.firebasestorage.app',
    measurementId: 'G-Z4Y099RGS6',
  );
}
